### ISSUE TITLE
Composer vulnerability

### ISSUE THREAD

**Issue by tjnurmin** [FloAppsLtd/Composer-CKEditor-Plugin-Installer#2]
1 composer/composer vulnerability found in composer.json 7 hours ago

## Remediation

Upgrade composer/composer to version 2.0.13 or later. For example:

```
"require": {
  "composer/composer": "2.0.13"
}
```

Always verify the validity and compatibility of suggestions with your codebase.
Details
GHSA-h5h8-pc6h-jvvx
high severity
Vulnerable versions: >= 2.0, < 2.0.13
Patched version: 2.0.13

URLs for Mercurial repositories in the root composer.json and package source download URLs are not sanitized correctly. Specifically crafted URL values allow commands to be executed in the HgDriver if hg/Mercurial is installed on the system.
Impact

    The impact to Composer users directly is limited as the composer.json file is typically under their own control and source download URLs can only be supplied by third party Composer repositories they explicitly trust to download and execute source code from, e.g. Composer plugins.
    The main impact is to services passing user input to Composer, including Packagist.org and Private Packagist. This allowed users to trigger remote command injection. The vulnerability has been patched on Packagist.org and Private Packagist within 12h of receiving the initial vulnerability report and based on a review of logs, to the best of our knowledge, was not abused by anyone.
    Other services/tools using VcsRepository/VcsDriver or derivatives may also be vulnerable and should upgrade their composer/composer dependency immediately

Patches

1.10.22 and 2.0.13 include patches for this issue.

**Comment by thukka** [comment]
Working on this.

**Comment by thukka** [comment]
@tjnurmin 
Changed

```
    "require-dev": {
        "composer/composer": "^1.3|^2.0"
    }
```

to

```
    "require-dev": {
        "composer/composer": "^2.0.13"
    }
```

If I understood correctly `composer-plugin-api` can stay the same. Shall I push the code?

**Comment by tjnurmin** [comment]
Yes.

**Comment by tjnurmin** [comment]
Closed via https://github.com/FloAppsLtd/Composer-CKEditor-Plugin-Installer/commit/aef05796666b14fda3ac97856e56564c43902437
